# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3e62bb0b3b70bc158727c72e190ddc388468f71344bed3f901abe8c36dbb5370406cd6519579e26e318ca851af0e940db2311041079cc6091cf7493c464dd5

test:
  secret_key_base: 3a4caed8bbc5e05931f69908197580b9091098ea041236f18970e80b9b9a4fc6a51496092dfc6b7a819a86a9009d617fb7351f79b3923862515ffc2cc5855aa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
